#!/usr/bin/env bash
# vim: ft=sh
npm install -g forever
test -f "${SUPERWATCHER_HOME}/watch" && rm "${SUPERWATCHER_HOME}/watch"
test -f "${SUPERWATCHER_HOME}/environment" && rm "${SUPERWATCHER_HOME}/environment"
test ! -d "${SUPERWATCHER_HOME}/var/log" && mkdir -p "${SUPERWATCHER_HOME}/var/log"
test ! -d "${SUPERWATCHER_HOME}/etc" && mkdir -p "${SUPERWATCHER_HOME}/etc"
