#!/usr/bin/env bash
# vim: ft=sh
source "${SUPERFORKER_ROOT}/src/env"
if [ ! -d "${ETC_DIR}" ]; then
    mkdir -p "${ETC_DIR}"
fi
if [ ! -d "${LOG_DIR}" ]; then
    mkdir -p "${LOG_DIR}"
fi
#force reinstall superforker
npm install -g "${SUPERFORKER_ROOT}"
npm install -g forever

