#!/usr/bin/env bash
# vim: ft=sh
source "${SUPERFORKER_ROOT}/src/env"
#lets ask forever if stuff is running from this directory
RUNNING=`forever list | grep "${ROOT}"`
WATCHDOG=`crontab -l | grep "${ROOT}"`
#only start if we aren't already running
if [ -z "${RUNNING}" ]; then
  if [ -e ${ETC_DIR}/environment/before_start ]; then
    "${ETC_DIR}/environment/before_start"
  fi
  superforker daemon ${PORT} "${LOG_DIR}" "${HANDLE_THIS}"
fi
#and put in a watchdog cron task to keep everything working
if [ -z "${WATCHDOG}" ]; then
  echo "Adding a watchdog"
  crontab -l > crontemp
  printf "* * * * *\texport ROOT=\"${ROOT}\"; source \"${SUPERFORKER_ROOT}/src/bootstrap\"; superforker watchdog > \"${LOG_DIR}/watchdog.log\" 2>&1\n" >> crontemp
  cat crontemp | crontab
  rm crontemp
fi
