#!/usr/bin/env bash
source "${SUPERFORKER_ROOT}/src/env"
#have forever stop the madness, and remove the watchdog cron job
superforker undaemon
WATCHDOG=`crontab -l | grep "${ROOT}"`
#wipe out the watchdog from the crontab
if [ -n "$WATCHDOG" ]; then
  echo "Removing the watchdog"
  crontab -l | grep -v "${ROOT}" | crontab
fi
