#! /usr/bin/env bash

touch "${SUPERWATCHER_HOME}/watchdog_run"
echo $USER > "${SUPERWATCHER_HOME}/user"

LOG_DIR="${SUPERWATCHER_HOME}/var/log"
if [ ! -d "${LOG_DIR}" ]; then
  mkdir -p "${LOG_DIR}"
fi

if [ $(uname) -eq "Darwin" ]; then
  MD5=md5
else
  MD5=md5sum
fi

#we need to make sure things are still running
RUNNING=`forever list | grep  "${LOG_DIR}"`
if [ -z "${RUNNING}" ]; then
  forever start --append -l "${LOG_DIR}/forever.log" -o "${LOG_DIR}/out.log" \
    -e "${LOG_DIR}/err.log" -c bash "${SUPERWATCHER_HOME}/main"
fi

#check on all watch repositories for updates
cat "${SUPERWATCHER_HOME}/watch" | xargs -I % "${SUPERWATCHER_HOME}/update_repo_as_needed" % >> "${SUPERWATCHER_HOME}/updates"

#special case here, restart if the environment has changed
if [ -f "${SUPERWATCHER_HOME}/environment" ]; then
    CURRENT_SIGNATURE=$(${MD5} "${SUPERWATCHER_HOME}/environment")
    PRIOR_SIGNATURE=$(cat "${SUPERWATCHER_HOME}/environment.md5") || $(echo -)
    if [ "${CURRENT_SIGNATURE}" != "${PRIOR_SIGNATURE}" ]; then
        echo "environment changed ${CURRENT_SIGNATURE} ${PRIOR_SIGNATURE}"
        echo -n ${CURRENT_SIGNATURE} > "${SUPERWATCHER_HOME}/environment.md5"
        forever restart "${SUPERWATCHER_HOME}/main"
    fi
fi
