#! /usr/bin/env bash

touch "${SUPERWATCHER_HOME}/watchdog_run"
echo $USER > "${SUPERWATCHER_HOME}/user"

cat "${SUPERWATCHER_HOME}/watch" | xargs ls >> "${SUPERWATCHER_HOME}/updates"
exit 0

source "${SUPERFORKER_ROOT}/src/env"
#make sure our exciting environment repository is up to date, and if it changed
#then we are going to need to restart
"${BIN}/update_repo_as_needed" "${ETC_DIR}/environment"
if [ $? == 100 ]; then
  echo "environment changed, stopping the server to pick up the changes"
  superforker stop
fi

"${BIN}/update_repo_as_needed" "${ETC_DIR}/handlers"
if [ $? == 100 ]; then
    echo "handlers changed, no need to stop and restart"
    if [ -e "${ETC_DIR}/handlers/on_update" ]; then
        pushd "${ETC_DIR}/handlers"
        ./on_update
        popd
    fi
fi

#call into the start, it's safe to call if we are already started, we promise
superforker start
