#! /usr/bin/env bash

#get your local path to this running superwatcher
SCRIPT_PATH="$( readlink "${BASH_SOURCE[0]}" )"
if [ -z "${SCRIPT_PATH}" ]; then
    SCRIPT_PATH="${BASH_SOURCE[0]}"
fi
SCRIPT_DIR="$( cd "$( dirname "${SCRIPT_PATH}" )" && pwd )"

#tracking that we ran, and who we ran as -- debug info in case you get lost
touch "${SUPERWATCHER_HOME}/watchdog_run"
echo $USER > "${SUPERWATCHER_HOME}/user"

#set up the environment before running an update
if [ -f "${SUPERWATCHER_HOME}/environment" ]; then
  source "${SUPERWATCHER_HOME}/environment"
fi

#check on all watch repositories for updates
if [ -f "${SUPERWATCHER_HOME}/watch" ]; then
  cat "${SUPERWATCHER_HOME}/watch" | xargs -I % "${SUPERWATCHER_HOME}/update_repo_as_needed" %
fi

